# Generated by Django 3.2.5 on 2021-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mainbase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainbase',
            name='chackbox',
        ),
        migrations.AddField(
            model_name='mainbase',
            name='inputOrOutput',
            field=models.TextField(default='Kirdi'),
        ),
    ]
