# Generated by Django 3.2.5 on 2021-07-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210712_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbase',
            name='byWhom',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mainbase',
            name='inputOrOutput',
            field=models.TextField(default='Yuk bazaga kirdi'),
        ),
    ]
