# Generated by Django 3.2.5 on 2021-07-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mainbase_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainbase',
            old_name='price',
            new_name='insidePrice',
        ),
        migrations.AddField(
            model_name='mainbase',
            name='outsidePrice',
            field=models.IntegerField(default=0),
        ),
    ]
