# Generated by Django 3.2.5 on 2021-07-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_qarz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qarz',
            old_name='qarzDate',
            new_name='oxirgiQarzBerganVaqti',
        ),
    ]
