# Generated by Django 3.2.5 on 2021-07-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_qarzdate_qarz_oxirgiqarzberganvaqti'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarz',
            name='totalSum',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
