# Generated by Django 3.2.5 on 2021-07-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210713_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputqarz',
            name='totalLend',
            field=models.IntegerField(default=0),
        ),
    ]
