# Generated by Django 3.2.5 on 2021-07-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_inputqarz_totallend'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarz',
            name='debt',
            field=models.BooleanField(default=False),
        ),
    ]
