# Generated by Django 3.2.5 on 2021-07-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_qarz_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputqarz',
            name='byWhom',
            field=models.TextField(default=''),
        ),
    ]
