# Generated by Django 3.2.5 on 2021-07-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_inputqarz_bywhom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='img',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
