# Generated by Django 3.2.5 on 2021-07-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_home_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
