# Generated by Django 3.2.5 on 2021-07-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_home_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarz',
            name='orginalPrice',
            field=models.IntegerField(default=0),
        ),
    ]
