# Generated by Django 3.2.5 on 2021-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210714_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputqarz',
            name='payAgent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
