# Generated by Django 3.2.5 on 2021-07-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210714_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='payagent',
            name='lastPayAgent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
