# Generated by Django 3.2.5 on 2021-07-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_qarz_aftercreatedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputqarz',
            name='afterCreateDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
