# Generated by Django 3.2.5 on 2021-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_inputqarz_aftercreatedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainbase',
            name='inputOrOutput',
        ),
        migrations.AddField(
            model_name='mainbase',
            name='debt',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='mainbase',
            name='lastLendDebt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mainbase',
            name='oxirgiQarzBerganVaqti',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mainbase',
            name='qarzSum',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mainbase',
            name='totalLend',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
