# Generated by Django 3.2.5 on 2021-07-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210718_0529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputQarz',
        ),
        migrations.AddField(
            model_name='qarz',
            name='oxirgiQarzBerganVaqti',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='qarz',
            name='qarzSum',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='qarz',
            name='totalLend',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
