# Generated by Django 3.2.5 on 2021-07-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210722_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfProduct', models.TextField()),
                ('kg', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('totalSum', models.IntegerField(blank=True, default=0)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('byWhom', models.TextField(default='')),
                ('debt', models.BooleanField(default=False, null=True)),
                ('lastLendDebt', models.IntegerField(default=0, null=True)),
                ('debtSum', models.IntegerField(default=0, null=True)),
                ('oxirgiQarzBerganVaqti', models.DateField(null=True)),
                ('totalLend', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
