# Generated by Django 3.2.5 on 2021-07-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_baza'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='kgOrg',
            field=models.IntegerField(default=0),
        ),
    ]
