# Generated by Django 3.2.5 on 2021-07-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_baza_kgorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='changed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
