# Generated by Django 3.2.5 on 2021-07-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_howmuch'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='showToAgent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
