# Generated by Django 3.2.5 on 2021-07-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20210725_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='howMuch',
        ),
    ]
