# Generated by Django 3.2.5 on 2021-08-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_delete_howmuch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza',
            name='kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='baza',
            name='kgOrg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mainbase',
            name='kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='kg',
            field=models.FloatField(default=0, null=True),
        ),
    ]
