# Generated by Django 3.2.5 on 2021-08-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20210816_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeMoneyFromBazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TakeMoney', models.IntegerField(default=0, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('who', models.TextField(default='')),
            ],
        ),
    ]
